from enum import StrEnum

UNAVAILABLE_RETRY_AFTER_SECONDS = 1


class DatabaseOutageCode(StrEnum):
    CONNECT_FAILED = "DATABASE_UNAVAILABLE_001"
    CONNECTION_LOST = "DATABASE_UNAVAILABLE_002"
    POOL_EXHAUSTED = "DATABASE_UNAVAILABLE_003"
    STATEMENT_TIMEOUT = "DATABASE_TIMEOUT_001"
