"""Emit the entity-type taxonomy that frontends generate their types from.
Run: ``uv run python scripts/export_entity_type_contract.py``

Values only, no labels — display is the consumer's job. This exists because the
taxonomy had no export at all: every consumer outside Python hand-copied it, and
``tr-crm-frontend``'s copy had drifted to ``comment`` for ``activity.comment``
while missing seven values outright.
"""

from __future__ import annotations

import json
from pathlib import Path

from tr_shared.contracts.entity_types import EntityType
from tr_shared.contracts.taxonomy import Feature

CONTRACT_PATH = Path(__file__).resolve().parent.parent / "contracts" / "entity-types.json"

HEADER = "GENERATED by scripts/export_entity_type_contract.py — do not edit by hand."


def build_contract() -> dict[str, object]:
    return {
        "$comment": HEADER,
        # Declaration order, not sorted: the enum's order is the taxonomy's own
        # grouping (feature by feature), and a consumer diffing the two lists by eye
        # should see the same shape on both sides.
        "entity_type": [member.value for member in EntityType],
        # Exported alongside because `EntityType.feature()` derives one from the other:
        # a consumer that filters by feature needs both lists to agree, and deriving
        # the feature list by splitting on "." would re-implement that method.
        "feature": [member.value for member in Feature],
    }


def render() -> str:
    return json.dumps(build_contract(), indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {CONTRACT_PATH.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
