import json
from pathlib import Path

from tr_shared.contracts.headers import HttpHeader

CONTRACT_PATH = Path(__file__).resolve().parent.parent / "contracts" / "http-headers.json"

HEADER = "GENERATED by scripts/export_http_header_contract.py — do not edit by hand."


def build_contract() -> dict[str, object]:
    return {
        "$comment": HEADER,
        "http_header": {member.name: member.value for member in HttpHeader},
    }


def render() -> str:
    return json.dumps(build_contract(), indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    CONTRACT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {CONTRACT_PATH.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
