"""Typed event payloads. EventPayload is the strict base; per-feature modules
hold the {Feature}{Event}{Vn} models. Additive within a Vn; breaking = new Vn."""

from tr_shared.events.payloads._base import EventPayload
from tr_shared.events.payloads.activity import (
    ActivityCommentAddedV1,
    ActivityCommentDeletedV1,
    ActivityCommentEditedV1,
    ActivityLogCreatedV1,
)
from tr_shared.events.payloads.admin import (
    AdminAgentGroupCreatedV1,
    AdminAgentGroupDeletedV1,
    AdminAgentGroupUpdatedV1,
    AdminAssignmentRuleCreatedV1,
    AdminAssignmentRuleDeletedV1,
    AdminAssignmentRuleUpdatedV1,
    AdminLeadScoringCreatedV1,
    AdminLeadScoringDeletedV1,
    AdminLeadScoringUpdatedV1,
    AdminLeadSourceCreatedV1,
    AdminLeadSourceDeletedV1,
    AdminLeadSourceUpdatedV1,
    AdminModuleConfigurationUpdatedV1,
    AdminNurtureCampaignCreatedV1,
    AdminNurtureCampaignUpdatedV1,
    IntegrationPlatformEventV1,
)
from tr_shared.events.payloads.auth import (
    AdminPortalAgentPromotedV1,
    AdminRoleAssignedV1,
    AdminUserCreatedV1,
    AdminUserUpdatedV1,
    PortalAgentIdentityV1,
)
from tr_shared.events.payloads.cms import (
    CMSBlogEventV1,
    CMSBlogUpdatedV1,
    CMSLandingPageContextV1,
    CMSLandingPageMediaV1,
    CMSLandingPagePublishedV1,
    CMSPageApprovedV1,
    CMSPageEventV1,
    CMSPagePublishedV1,
    CMSPageRejectedV1,
    CMSPageReviewRequestedV1,
    CMSPageUpdatedV1,
)
from tr_shared.events.payloads.finance import (
    FinanceCardTransactionImportedV1,
    FinanceCardTransactionMatchedV1,
    FinanceExpenseEventV1,
    FinanceExpenseRejectedV1,
    FinanceInvoiceEventV1,
)
from tr_shared.events.payloads.hr import (
    HRApplicationStageChangedV1,
    HRApplicationSubmittedV1,
    HRAttendanceCorrectionV1,
    HREventV1,
    HRJobPostingClosedV1,
    HRJobPostingPublishedV1,
    HRManualEntryCreatedV1,
    HRSyncFailedV1,
)
from tr_shared.events.payloads.lead import (
    LeadAssignedV1,
    LeadCreatedV1,
    LeadEventV1,
    LeadFollowupDueV1,
    LeadQualifiedV1,
)
from tr_shared.events.payloads.listing import (
    ListingAuditEventV1,
    ListingDeletedV1,
    ListingExpiredV1,
    ListingPfEventV1,
    ListingRepublishedV1,
    ListingSaleV1,
)
from tr_shared.events.payloads.lms import (
    LMSQuizAssignedV1,
    LMSQuizExpiredV1,
    LMSQuizGeneratedV1,
)
from tr_shared.events.payloads.notification import (
    NotificationLeadOverdueRequestedV1,
    NotificationSentV1,
)
from tr_shared.events.payloads.task import (
    TaskAssignedV1,
    TaskCoAssignedV1,
    TaskCreatedV1,
    TaskDueSoonV1,
    TaskEventV1,
    TaskStatusChangedV1,
    TaskWatcherAddedV1,
)
from tr_shared.events.payloads.wam import (
    WAMLeadQualifiedV1,
    WAMQualificationResultV1,
)

__all__ = [
    "EventPayload",
    "ActivityCommentAddedV1",
    "ActivityCommentDeletedV1",
    "ActivityCommentEditedV1",
    "ActivityLogCreatedV1",
    "AdminAgentGroupCreatedV1",
    "AdminAgentGroupDeletedV1",
    "AdminAgentGroupUpdatedV1",
    "AdminAssignmentRuleCreatedV1",
    "AdminAssignmentRuleDeletedV1",
    "AdminAssignmentRuleUpdatedV1",
    "AdminLeadScoringCreatedV1",
    "AdminLeadScoringDeletedV1",
    "AdminLeadScoringUpdatedV1",
    "AdminLeadSourceCreatedV1",
    "AdminLeadSourceDeletedV1",
    "AdminLeadSourceUpdatedV1",
    "AdminModuleConfigurationUpdatedV1",
    "AdminNurtureCampaignCreatedV1",
    "AdminNurtureCampaignUpdatedV1",
    "IntegrationPlatformEventV1",
    "AdminPortalAgentPromotedV1",
    "AdminRoleAssignedV1",
    "AdminUserCreatedV1",
    "PortalAgentIdentityV1",
    "AdminUserUpdatedV1",
    "CMSBlogEventV1",
    "CMSBlogUpdatedV1",
    "CMSLandingPageContextV1",
    "CMSLandingPageMediaV1",
    "CMSLandingPagePublishedV1",
    "CMSPageApprovedV1",
    "CMSPageEventV1",
    "CMSPagePublishedV1",
    "CMSPageRejectedV1",
    "CMSPageReviewRequestedV1",
    "CMSPageUpdatedV1",
    "FinanceCardTransactionImportedV1",
    "FinanceCardTransactionMatchedV1",
    "FinanceExpenseEventV1",
    "FinanceExpenseRejectedV1",
    "FinanceInvoiceEventV1",
    "HRApplicationStageChangedV1",
    "HRApplicationSubmittedV1",
    "HRAttendanceCorrectionV1",
    "HREventV1",
    "HRJobPostingClosedV1",
    "HRJobPostingPublishedV1",
    "HRManualEntryCreatedV1",
    "HRSyncFailedV1",
    "LeadAssignedV1",
    "LeadCreatedV1",
    "LeadEventV1",
    "LeadFollowupDueV1",
    "LeadQualifiedV1",
    "ListingAuditEventV1",
    "ListingDeletedV1",
    "ListingExpiredV1",
    "ListingPfEventV1",
    "ListingRepublishedV1",
    "ListingSaleV1",
    "LMSQuizAssignedV1",
    "LMSQuizExpiredV1",
    "LMSQuizGeneratedV1",
    "NotificationLeadOverdueRequestedV1",
    "NotificationSentV1",
    "TaskAssignedV1",
    "TaskCoAssignedV1",
    "TaskCreatedV1",
    "TaskDueSoonV1",
    "TaskEventV1",
    "TaskStatusChangedV1",
    "TaskWatcherAddedV1",
    "WAMLeadQualifiedV1",
    "WAMQualificationResultV1",
]
